name: Deploy

on:
  push:
    branches:
      - main

jobs:

  monitor:
    name: Deploy Monitor
    runs-on: ubuntu-latest

    steps:
      - name: Deploy monitor server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.MONITOR_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/tennis-bot
            bash scripts/update.sh

  booking:
    name: Deploy Booking
    runs-on: ubuntu-latest

    steps:
      - name: Deploy booking server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.BOOKING_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/tennis-bot
            bash scripts/update.sh
